[[hooks]]
stage = "pre_build"
command = "sh"
command_arguments = ["-c", "echo 'Building power law simulation...'"]

[build]
target = "index.html"
dist = "dist"

[serve]
addresses = ["0.0.0.0"]
port = 8080
open = true
